### ISSUE TITLE
Novos arquivos a serem ignorados

### ISSUE THREAD

**Issue by igoryy** [tagawaxd/projetolocadora#2]
Bom dia, 
Deem uma olhada no repositório, ainda existem arquivos de configurações das suas IDE, eles não precisam estar dentro do repositório , estou anexando uma imagem de alguns arquivos, porem existe outros

![image](https://user-images.githubusercontent.com/67551720/88190067-36411780-cc10-11ea-9a36-9f2efbaa7812.png)

**Comment by tagawaxd** [comment]
Foi adicionada uma regra ao arquivo **.gitignore** e estes arquivos vão passar a ser ignorados nas próximas atualizações (commit).
